import streamlit as st
import sqlite3
import pandas as pd
import re
import plotly.graph_objects as go
import smtplib
from fpdf import FPDF
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from auth import authenticate_user, logout_button

# -----------------------------
# CARETAKER ALERT AGENT
# -----------------------------

def send_caretaker_email(receiver_email, alert_type):

    sender_email = "7sdhanush@gmail.com"

    app_password = "qnxu yevi mfkw bdfe"

    if alert_type == "FIRST":

        subject = "🚨 First Medication Alert"

        body = """
Patient has missed medicines 3 times.

Please remind the patient to take medicines regularly.

Generated by Smart Healthcare Assistant.
"""

    elif alert_type == "SECOND":

        subject = "⚠ Second Medication Alert"

        body = """
Patient has missed medicines 7 times.

Immediate caretaker attention is recommended.

Generated by Smart Healthcare Assistant.
"""

    else:

        subject = "🆘 Critical Medication Alert"

        body = """
Patient has missed medicines 10 times.

Urgent caretaker intervention required.

Generated by Smart Healthcare Assistant.
"""

    msg = MIMEMultipart()

    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg["Subject"] = subject

    msg.attach(
        MIMEText(body, "plain")
    )

    server = smtplib.SMTP(
        "smtp.gmail.com",
        587
    )

    server.starttls()

    server.login(
        sender_email,
        app_password
    )

    server.send_message(msg)

    server.quit()

# ---------------------------------------
# PATIENT MEDICATION ADHERENCE REPORT
# ---------------------------------------

def send_caretaker_report_email(receiver_email, report):

    sender_email = "7sdhanush@gmail.com"
    app_password = "qnxu yevi mfkw bdfe"

    subject = "📄 Patient Medication Adherence Report"

    msg = MIMEMultipart()

    msg["From"] = sender_email
    msg["To"] = receiver_email
    msg["Subject"] = subject

    msg.attach(
        MIMEText(report, "plain")
    )

    server = smtplib.SMTP(
        "smtp.gmail.com",
        587
    )

    server.starttls()

    server.login(
        sender_email,
        app_password
    )

    server.send_message(msg)

    server.quit()

# -----------------------------
# PDF REPORT GENERATOR
# -----------------------------

def create_health_pdf(
    total_medicines,
    total_missed,
    symptom_count,
    latest_symptom,
    caretaker,
    health_score,
    adherence
):

    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, "SMART HEALTHCARE ASSISTANT REPORT", ln=True, align="C")

    pdf.ln(8)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Health Overview", ln=True)

    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"Total Medicines: {total_medicines}", ln=True)
    pdf.cell(0, 8, f"Total Missed Doses: {total_missed}", ln=True)
    pdf.cell(0, 8, f"Symptoms Logged: {symptom_count}", ln=True)

    if latest_symptom:
        pdf.cell(
            0,
            8,
            f"Latest Symptom: {latest_symptom[0]} ({latest_symptom[1]})",
            ln=True
        )
    else:
        pdf.cell(0, 8, "Latest Symptom: No symptoms logged", ln=True)

    pdf.ln(5)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Caretaker Details", ln=True)

    pdf.set_font("Arial", "", 11)

    if caretaker:
        pdf.cell(0, 8, f"Caretaker Name: {caretaker[0]}", ln=True)
        pdf.cell(0, 8, f"Phone: {caretaker[1]}", ln=True)
        pdf.cell(0, 8, f"Email: {caretaker[2]}", ln=True)
    else:
        pdf.cell(0, 8, "Caretaker Details: Not Available", ln=True)

    pdf.ln(5)

    risk = (
        "Low Risk"
        if health_score >= 90
        else "Moderate Risk"
        if health_score >= 70
        else "High Risk"
    )

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Health Assessment", ln=True)

    pdf.set_font("Arial", "", 11)
    pdf.cell(0, 8, f"Health Score: {health_score}/100", ln=True)
    pdf.cell(0, 8, f"Medicine Adherence: {adherence:.1f}%", ln=True)
    pdf.cell(0, 8, f"Risk Level: {risk}", ln=True)

    pdf.ln(5)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "Health Summary", ln=True)

    pdf.set_font("Arial", "", 11)
    pdf.multi_cell(
        0,
        8,
        f"""
Total Medicines Added: {total_medicines}
Total Missed Doses: {total_missed}
Symptoms Logged: {symptom_count}
Medicine Adherence: {adherence:.1f}%
Health Score: {health_score}/100
Risk Level: {risk}
"""
    )

    pdf.ln(5)

    pdf.set_font("Arial", "I", 10)
    pdf.multi_cell(
        0,
        8,
        "Generated by Smart Healthcare Assistant. This report helps patients and caretakers review medicine adherence, symptoms, health score, and risk level."
    )

    return pdf.output(dest="S").encode("latin-1")

# -----------------------------
# PAGE CONFIG
# -----------------------------

st.set_page_config(
    page_title="Smart Healthcare Assistant",
    layout="wide"
)

if "alert_message" not in st.session_state:
    st.session_state.alert_message = ""

if "alert_type" not in st.session_state:
    st.session_state.alert_type = ""

st.markdown("""
<style>

.stApp {

    background: linear-gradient(
        -45deg,
        #e0f2fe,
        #dbeafe,
        #f0f9ff,
        #e0f7fa
    );

    background-size: 400% 400%;

    animation: gradientBG 15s ease infinite;
}

@keyframes gradientBG {

    0% {
        background-position: 0% 50%;
    }

    50% {
        background-position: 100% 50%;
    }

    100% {
        background-position: 0% 50%;
    }
}
   .stButton > button {

    background-color: #3B82F6;

    color: white;

    border-radius: 10px;

    border: none;

    transition: all 0.3s ease;
}

.stButton > button:hover {

    background-color: #14B8A6;

    color: white;

    transform: scale(1.05);

    box-shadow: 0px 5px 15px rgba(20,184,166,0.4);
}

.stDownloadButton > button:hover {

    background-color: #14B8A6;

    color: white;

    transform: scale(1.05);

    box-shadow: 0px 5px 15px rgba(20,184,166,0.4);
}

</style>
""", unsafe_allow_html=True)

# -----------------------------
# PROFESSIONAL HEADER
# -----------------------------

st.markdown("""
<style>

.hero {

    padding: 30px;

    border-radius: 20px;

    background: linear-gradient(
        135deg,#14B8A6,#3B82F6
    );

    text-align: center;

    color: white;

    box-shadow:
    0px 10px 25px rgba(59,130,246,0.25);

    margin-bottom: 20px;
}

.hero h1 {

    font-size: 50px;

    margin-bottom: 10px;
}

.hero h4 {

    font-size: 20px;

    font-weight: 400;
}

</style>
            
""", unsafe_allow_html=True)



# -----------------------------
# DATABASE CONNECTION
# -----------------------------

conn = sqlite3.connect("database/healthcare.db", check_same_thread=False)
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS health_history(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT,
    health_score INTEGER
)
""")

conn.commit()

cursor.execute("""
CREATE TABLE IF NOT EXISTS medicines(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    medicine_name TEXT,
    medicine_time TEXT,
    status TEXT
)
""")

conn.commit()

# -----------------------------
# SIDEBAR
# -----------------------------
st.sidebar.markdown("## 🏥 Healthcare Navigation")
st.sidebar.success("🟢 System Online")

logout_button()

menu = st.sidebar.selectbox(
    "Select Module",
    [
        "Dashboard",
        "Medicine Reminder",
        "Symptom Logger",
        "Symptom Analyzer",
        "Drug Safety Checker",
        "Health Report",
        "Expense Intelligence",
        "AI Health Risk Forecaster",
        "AI Health Improvement Coach",
        "Smart Medication Planner",
        "AI Chatbot",
        "Caretaker Settings"
    ]
)

# -----------------------------
# DASHBOARD
# -----------------------------

if menu == "Dashboard":

    st.markdown("""
    <div class="hero">
    <h1>❤️ PulseNova</h1>
    <h1>🏥 Smart Healthcare Assistant</h1>

    <h4>
    AI-Powered Personal Healthcare Companion
    </h4>

    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div style="
    text-align:center;
    font-size:18px;
    font-weight:bold;
    color:#2563EB;
    padding:10px;
    margin-bottom:20px;
    ">

    ✨ Smart Medicine Tracking
    &nbsp;&nbsp;&nbsp;&nbsp;

    🤖 AI Health Analysis
    &nbsp;&nbsp;&nbsp;&nbsp;

    📋 Health Reports
    &nbsp;&nbsp;&nbsp;&nbsp;

    💊 Medicine Reminder
    &nbsp;&nbsp;&nbsp;&nbsp;

    ⚠ Drug Safety Checker
    &nbsp;&nbsp;&nbsp;&nbsp;
                
    📝 Symptom Logger
    &nbsp;&nbsp;&nbsp;&nbsp;
                
    👨‍👩‍👧 Caretaker Settings
    &nbsp;&nbsp;&nbsp;&nbsp;
                
    💰 Expense Intelligence
    &nbsp;&nbsp;&nbsp;&nbsp;
                
    🩺 AI Health Risk Forecaster
    &nbsp;&nbsp;&nbsp;&nbsp;
                
    🎯 AI Health Improvement Coach
    &nbsp;&nbsp;&nbsp;&nbsp;
                
    ⏰ Smart Medication Planner
                
    
    </div>
    """, unsafe_allow_html=True)

    st.header("📊 Dashboard")

    cursor.execute("SELECT COUNT(*) FROM medicines")
    medicine_count = cursor.fetchone()[0]

    cursor.execute("SELECT COUNT(*) FROM symptoms")
    symptom_count = cursor.fetchone()[0]

    cursor.execute("""
    SELECT COUNT(*)
    FROM medicines
    WHERE alert_level > 0
    """)

    active_alerts = cursor.fetchone()[0]

    col1, col2, col3 = st.columns(3)

    with col1:

        st.markdown(f"""
        <div style="
        background:linear-gradient(135deg,#667eea,#764ba2);
        padding:25px;
        border-radius:20px;
        text-align:center;
        color:white;
        box-shadow:0px 5px 15px rgba(0,0,0,0.15);
        ">
        <h1>💊</h1>
        <h2>{medicine_count}</h2>
        <h4>Medicines</h4>
        </div>
        """, unsafe_allow_html=True)

    with col2:

        st.markdown(f"""
        <div style="
        background:linear-gradient(135deg,#f093fb,#f5576c);
        padding:25px;
        border-radius:20px;
        text-align:center;
        color:white;
        box-shadow:0px 5px 15px rgba(0,0,0,0.15);
        ">
        <h1>🤒</h1>
        <h2>{symptom_count}</h2>
        <h4>Symptoms Logged</h4>
        </div>
        """, unsafe_allow_html=True)

    with col3:

        st.markdown(f"""
        <div style="
        background:linear-gradient(135deg,#43e97b,#38f9d7);
        padding:25px;
        border-radius:20px;
        text-align:center;
        color:white;
        box-shadow:0px 5px 15px rgba(0,0,0,0.15);
        ">
        <h1>🚨</h1>
        <h2>{active_alerts}</h2>
        <h4>Safety Alerts</h4>
        </div>
        """, unsafe_allow_html=True)

    st.markdown("""
    <div style="
    background:linear-gradient(135deg,#ff9a9e,#fad0c4);
    padding:25px;
    border-radius:20px;
    text-align:center;
    margin-top:20px;
    box-shadow:0px 5px 15px rgba(0,0,0,0.15);
    ">

    <h2>🏥 Welcome to Smart Healthcare Assistant</h2>

    <p style="font-size:18px;">
    Monitor medicines, analyze symptoms,
    check drug interactions and generate
    health reports using AI.
    </p>

    </div>
    """, unsafe_allow_html=True)

# -----------------------------
# MEDICINE REMINDER
# -----------------------------

elif menu == "Medicine Reminder":

    st.header("💊 Medicine Reminder")

    if st.session_state.alert_message:

        st.subheader("🚨 Active Alert")

        if st.session_state.alert_type == "warning":

            st.warning(
                st.session_state.alert_message
            )

        else:

            st.error(
                st.session_state.alert_message
            )

    medicine_name = st.text_input("Medicine Name")

    medicine_time = st.time_input("Medicine Time")

    if st.button("Add Medicine"):

        cursor.execute(
            """
            INSERT INTO medicines
            (medicine_name, medicine_time, status, missed_count)
            VALUES (?, ?, ?, ?)
            """,
            (
                medicine_name,
                str(medicine_time),
                "Pending",
                0
            )
        )

        conn.commit()

        st.success("Medicine Added Successfully")

    st.subheader("Saved Medicines")

    cursor.execute("SELECT * FROM medicines")

    medicines = cursor.fetchall()

    if medicines:

        for medicine in medicines:

            status = medicine[3]

            if status == "Taken":
                badge = "🟢 Taken"

            elif status == "Missed":
                badge = "🔴 Missed"

            else:
                badge = "🟡 Pending"

            st.markdown(f"""
<div style="
background:white;
padding:20px;
border-radius:15px;
box-shadow:0px 4px 10px rgba(0,0,0,0.1);
margin-bottom:15px;
border-left:5px solid #2563EB;
">

<h4>💊 {medicine[1]}</h4>

<p>⏰ Time: {medicine[2]}</p>

<p>📌 Status: {badge}</p>

</div>
""", unsafe_allow_html=True)

            col1, col2 = st.columns(2)

            with col1:

                if st.button(
                    "✅ Taken",
                    key=f"taken_{medicine[0]}"
                ):

                    cursor.execute(
                        """
                        UPDATE medicines
                        SET status = 'Taken',
                            missed_count = 0,
                            alert_level = 0
                        WHERE id = ?
                        """,
                        (medicine[0],)
                    )

                    conn.commit()

                    st.success(
                        "Medicine Marked as Taken"
                    )
                    st.session_state.alert_message = ""
                    st.session_state.alert_type = ""
                    
                

            with col2:

                if st.button(
                    "❌ Missed",
                    key=f"missed_{medicine[0]}"
                ):

                    cursor.execute(
                        """
                        UPDATE medicines
                        SET status = 'Missed'
                        WHERE id = ?
                        """,
                        (medicine[0],)
                    )

                    conn.commit()

                    cursor.execute(
                        """
                        UPDATE medicines
                        SET missed_count = missed_count + 1
                        WHERE id = ?
                        """,
                        (medicine[0],)
                    )

                    conn.commit()

                    cursor.execute(
                        """
                        SELECT missed_count, alert_level
                        FROM medicines
                        WHERE id = ?
                        """,
                        (medicine[0],)
                    )

                    result = cursor.fetchone()

                    count = result[0]
                    alert_level = result[1]

                    st.warning(
                        f"Medicine Missed {count} times"
                    )

                    cursor.execute(
                        """
                        SELECT email
                        FROM caretaker
                        ORDER BY id DESC
                        LIMIT 1
                        """
                    )

                    caretaker = cursor.fetchone()

                    if caretaker:

                        caretaker_email = caretaker[0]

                        # Critical Alert (10 Misses)

                        if count >= 10 and alert_level < 3:

                            send_caretaker_email(
                                caretaker_email,
                                "CRITICAL"
                            )

                            cursor.execute(
                                """
                                UPDATE medicines
                                SET alert_level = 3
                                WHERE id = ?
                                """,
                                (medicine[0],)
                            )

                            conn.commit()

                            st.session_state.alert_message = \
                            f"🆘 Critical Alert Sent To Caretaker ({caretaker_email})"

                            st.session_state.alert_type = "critical"
                            st.error(
                                f"🆘 Critical Alert Sent To Caretaker ({caretaker_email})"
                            )

                        # Second Alert (7 Misses)

                        elif count >= 7 and alert_level < 2:

                            send_caretaker_email(
                                caretaker_email,
                                "SECOND"
                            )

                            cursor.execute(
                                """
                                UPDATE medicines
                                SET alert_level = 2
                                WHERE id = ?
                                """,
                                (medicine[0],)
                            )

                            conn.commit()

                            st.session_state.alert_message = \
                            f"⚠ Second Alert Sent To Caretaker ({caretaker_email})"

                            st.session_state.alert_type = "warning"
                            st.warning(
                                f"⚠ Second Alert Sent To Caretaker ({caretaker_email})"
                            )

                        # First Alert (3 Misses)

                        elif count >= 3 and alert_level < 1:

                            send_caretaker_email(
                                caretaker_email,
                                "FIRST"
                            )

                            cursor.execute(
                                """
                                UPDATE medicines
                                SET alert_level = 1
                                WHERE id = ?
                                """,
                                (medicine[0],)
                            )

                            conn.commit()

                            st.session_state.alert_message = \
                            f"🚨 First Alert Sent To Caretaker ({caretaker_email})"

                            st.session_state.alert_type = "error"
                            st.error(
                                f"🚨 First Alert Sent To Caretaker ({caretaker_email})"
                            )

                               
    else:

        st.info("No medicines added.")

# -----------------------------
# SYMPTOM LOGGER
# -----------------------------

elif menu == "Symptom Logger":

    st.header("📝 Symptom Logger")

    st.info(
        "Record symptoms daily so the system can track patient health changes over time."
    )

    symptom = st.text_input(
        "Enter Symptom",
        placeholder="Example: Fever, Headache, Chest Pain"
    )

    severity = st.selectbox(
        "Select Severity",
        [
            "Low",
            "Medium",
            "High"
        ]
    )

    notes = st.text_area(
        "Additional Notes",
        placeholder="Example: Fever since morning, mild headache, body pain"
    )

    if st.button("Save Symptom"):

        if not symptom.strip():

            st.warning(
                "Please enter a symptom."
            )

        else:

            today = datetime.now().strftime("%d-%m-%Y")

            cursor.execute(
                """
                INSERT INTO symptoms
                (symptom, severity, notes, date)
                VALUES (?, ?, ?, ?)
                """,
                (symptom, severity, notes, today)
            )

            conn.commit()

            st.success(
                "✅ Symptom Logged Successfully"
            )

    st.subheader("📋 Logged Symptoms")

    cursor.execute(
        """
        SELECT symptom, severity, notes, date
        FROM symptoms
        ORDER BY id DESC
        """
    )

    symptoms = cursor.fetchall()

    if symptoms:

        for item in symptoms:

            if item[1] == "High":
                severity_badge = "🔴 High"

            elif item[1] == "Medium":
                severity_badge = "🟡 Medium"

            else:
                severity_badge = "🟢 Low"

            st.markdown(f"""
<div style="
background:white;
padding:18px;
border-radius:15px;
box-shadow:0px 4px 10px rgba(0,0,0,0.1);
margin-bottom:15px;
border-left:5px solid #EF4444;
">

<h4>🤒 {item[0]}</h4>

<p>📊 Severity: {severity_badge}</p>

<p>📝 Notes: {item[2]}</p>

<p>📅 Date: {item[3]}</p>

</div>
""", unsafe_allow_html=True)

    else:

        st.info(
            "No symptoms logged yet."
        )       
    
# -----------------------------
# SYMPTOM ANALYZER
# -----------------------------

elif menu == "Symptom Analyzer":

    import google.generativeai as genai
    
    try:
        GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]
    except:
        from config import GEMINI_API_KEY

    genai.configure(api_key=GEMINI_API_KEY)

    st.header("🤒 Symptom Analyzer")

    symptoms = st.text_area(
        "Enter Symptoms",
        placeholder="Fever, Headache, Body Pain"
    )

    if st.button("Analyze Symptoms"):

        with st.spinner("Analyzing Symptoms..."):

            model = genai.GenerativeModel("gemini-2.5-flash")

            prompt = f"""
            Analyze the following symptoms:

            {symptoms}

            Give:
            1. Possible Condition
            2. Severity (Low/Medium/High)
            3. Recommendation

            Keep the response simple.
            """

            try:

                response = model.generate_content(prompt)

                st.write(response.text)

            except Exception as e:

                st.error(
                    "⚠️ Gemini API limit reached. Please try again later."
                )

# -----------------------------
# DRUG SAFETY CHECKER
# -----------------------------

elif menu == "Drug Safety Checker":

    import pandas as pd

    st.header("⚠️ Drug Safety Checker")

    st.info(
    "Enter two medicines to check for possible drug interactions and safety recommendations."
)

    drug1 = st.text_input("Medicine 1")

    drug2 = st.text_input("Medicine 2")

    if st.button("Check Safety"):

      if not drug1 or not drug2:

        st.warning(
            "Please enter both medicine names."
        )

      else:

        df = pd.read_csv("data/drug_interactions.csv")

        found = False

        for index, row in df.iterrows():

        
            if (
                (drug1.strip().lower() == row["Drug1"].lower()
                and drug2.strip().lower() == row["Drug2"].lower())
                or
                (drug1.strip().lower() == row["Drug2"].lower()
                and drug2.strip().lower() == row["Drug1"].lower())
            ):

                if row["Risk"] == "High":

                    st.error("🚨 High Risk Interaction")

                elif row["Risk"] == "Moderate":

                    st.warning("⚠ Moderate Risk Interaction")

                else:

                    st.info("ℹ Interaction Detected")

                st.write("### Reason")
                st.write(row["Reason"])

                st.write("### Recommendation")

                if row["Risk"] == "High":

                    st.write(
                        "Consult a healthcare professional before combining these medicines."
                    )

                elif row["Risk"] == "Moderate":

                    st.write(
                        "Use only under medical supervision."
                    )

                else:

                    st.write(
                        "Follow the prescribed dosage and monitor symptoms."
                    )

                found = True
                break

        if not found:

            st.success("✅ No Major Interaction")

            st.write("### Reason")
            st.write(
                "No significant interaction is commonly known."
            )

            st.write("### Recommendation")
            st.write(
                "Generally considered safe when used as directed."
            )

# -----------------------------
# HEALTH REPORT
# -----------------------------

elif menu == "Health Report":

    st.header("📋 Health Report")

    # Total Medicines

    cursor.execute(
        "SELECT COUNT(*) FROM medicines"
    )

    total_medicines = cursor.fetchone()[0]

    # Total Missed Doses

    cursor.execute(
        "SELECT SUM(missed_count) FROM medicines"
    )

    result = cursor.fetchone()[0]

    total_missed = result if result else 0

    cursor.execute(
    """
    SELECT name, phone, email
    FROM caretaker
    ORDER BY id DESC
    LIMIT 1
    """
    )

    caretaker = cursor.fetchone()
    
    # Total Symptoms Logged

    cursor.execute(
        "SELECT COUNT(*) FROM symptoms"
    )

    symptom_count = cursor.fetchone()[0]

    # Latest Symptom

    cursor.execute(
        """
        SELECT symptom, severity
        FROM symptoms
        ORDER BY id DESC
        LIMIT 1
        """
    )

    latest_symptom = cursor.fetchone()

    # Dashboard Cards

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric(
            "💊 Total Medicines",
            total_medicines
        )

    with col2:
        st.metric(
            "❌ Missed Doses",
            total_missed
        )

    with col3:
        st.metric(
            "🚨 Active Alerts",
            1 if total_missed >= 3 else 0
        )

    with col4:
        st.metric(
            "🤒 Symptoms Logged",
            symptom_count
        )

    if latest_symptom:

        st.info(
            f"Latest Symptom: {latest_symptom[0]} ({latest_symptom[1]})"
        )

    if total_missed >= 3:

        st.error(
            "🚨 Caretaker Alert Triggered"
        )

    if caretaker:

        st.write(
            f"👤 Caretaker: {caretaker[0]}"
        )

        st.write(
            f"📞 Phone: {caretaker[1]}"
        )

        st.write(
            f"📧 Email: {caretaker[2]}"
        )

        st.write(
            "Patient has missed medicines repeatedly."
        )

    # ------------------------
    # STEP 4 - HEALTH SCORE
    # ------------------------

    health_score = 100 - (total_missed * 10)

    if health_score < 0:
        health_score = 0

    today = datetime.now().strftime("%d-%m-%Y")

    cursor.execute(
        """
        SELECT *
        FROM health_history
        WHERE date = ?
        """,
        (today,)
    )

    existing = cursor.fetchone()

    if existing is None:

        cursor.execute(
            """
            INSERT INTO health_history
            (date, health_score)
            VALUES (?, ?)
            """,
            (today, health_score)
        )

    else:

        cursor.execute(
            """
            UPDATE health_history
            SET health_score = ?
            WHERE date = ?
            """,
            (health_score, today)
        )

    conn.commit()

    # Health Score Display
    st.metric(
        "❤️ Health Score",
        f"{health_score}/100"
    )

    st.progress(
        health_score / 100
    )

    # Gauge Chart
    fig = go.Figure(
        go.Indicator(
            mode="gauge+number",
            value=health_score,
            title={"text": "Health Score"},
            gauge={
                "axis": {"range": [0, 100]},
                "bar": {"color": "#2563EB"},
                "steps": [
                    {"range": [0, 50], "color": "#FEE2E2"},
                    {"range": [50, 80], "color": "#FEF3C7"},
                    {"range": [80, 100], "color": "#DCFCE7"}
                ]
            }
        )
    )

    fig.update_layout(
        height=350
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )
    # ------------------------
    # STEP 5 - RISK LEVEL
    # ------------------------

    st.subheader("Risk Assessment")

    if health_score >= 90:

        st.success(
            "🟢 Low Risk"
        )

    elif health_score >= 70:

        st.warning(
            "🟡 Moderate Risk"
        )

    else:

        st.error(
            "🔴 High Risk"
        )

    # ------------------------
    # MEDICINE ADHERENCE
    # ------------------------

    if total_medicines > 0:

        adherence = (
            (total_medicines - total_missed)
            / total_medicines
        ) * 100

        if adherence < 0:
            adherence = 0

    else:

        adherence = 100

    st.metric(
        "💊 Medicine Adherence",
        f"{adherence:.1f}%"
    )
    # ------------------------
    # HEALTH SUMMARY
    # ------------------------
    st.subheader("📋 Health Summary")

    st.write(
        f"""
        Total Medicines Added: {total_medicines}

        Total Missed Doses: {total_missed}

        Medicine Adherence: {adherence:.1f}%

        Health Score: {health_score}/100
        """
    )
    st.info(
    "📊 Your health trend analysis is ready. Review the chart below."
)
    
    st.subheader("📈 Health Trend")

    cursor.execute("""
    SELECT date, health_score
    FROM health_history
    """)

    history = cursor.fetchall()

    if history:

        df = pd.DataFrame(
            history,
            columns=[
                "Date",
                "Health Score"
            ]
        )

        df["Date"] = pd.to_datetime(
           df["Date"],
           format="%d-%m-%Y"
        )

        df = df.sort_values("Date")

        df = df.drop_duplicates(
            subset=["Date"],
            keep="last"
        )

        fig = go.Figure()

        fig.add_trace(
            go.Scatter(
                x=df["Date"],
                y=df["Health Score"],
                mode="lines+markers",
                name="Health Score",
                line=dict(width=4),
                marker=dict(size=10)
            )
        )

        fig.update_layout(
            title="📈 Health Score Trend",
            xaxis_title="Date",
            yaxis_title="Health Score",
            yaxis=dict(range=[0, 100]),
            template="plotly_white",
            height=500
        )

        st.plotly_chart(
            fig,
            use_container_width=True
        )

    else:

        st.info("No Health History Available")
    
    # ------------------------
    # QUICK HEALTH STATUS
    # ------------------------
    st.subheader("💡 Quick Health Status")

    if health_score >= 90:

        st.success(
            "🟢 Good Health"
        )

    elif health_score >= 70:

        st.warning(
            "🟡 Moderate Risk"
        )

    else:

        st.error(
            "🔴 High Risk"
        )

    # ------------------------
    # AI HEALTH RECOMMENDATIONS
    # ------------------------

    import google.generativeai as genai
    
    try:
        GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]
    except:
        from config import GEMINI_API_KEY

    genai.configure(api_key=GEMINI_API_KEY)

    st.subheader("🤖 AI Health Recommendations")

    if st.button("Generate AI Recommendations"):

        with st.spinner("Generating Recommendations..."):

            model = genai.GenerativeModel(
                "gemini-2.5-flash"
            )

            prompt = f"""
            Generate personalized health recommendations.

            Total Medicines: {total_medicines}

            Missed Doses: {total_missed}

            Health Score: {health_score}

            Medicine Adherence: {adherence:.1f}%

            Give:
            1. Medication Advice
            2. Lifestyle Advice
            3. Diet Suggestion
            4. Warning if needed

            Keep the response short and simple.
            """

            try:

                response = model.generate_content(prompt)

                st.write(response.text)

            except Exception as e:

                st.error(
                    "⚠️ AI Recommendation service temporarily unavailable."
                )

    # ------------------------
    # DOWNLOAD HEALTH REPORT
    # ------------------------

    st.subheader("📄 Download Health Report")

    pdf_data = create_health_pdf(
        total_medicines,
        total_missed,
        symptom_count,
        latest_symptom,
        caretaker,
        health_score,
        adherence
    )

    st.download_button(
        label="📥 Download Health Report PDF",
        data=pdf_data,
        file_name="Health_Report.pdf",
        mime="application/pdf"
    )
    
# -----------------------------
# AI CHATBOT
# -----------------------------

elif menu == "AI Chatbot":

    import google.generativeai as genai
    try:
        GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]
    except:
        from config import GEMINI_API_KEY

    genai.configure(api_key=GEMINI_API_KEY)

    st.header("🤖 AI Health Chatbot")

    question = st.text_input(
        "Ask any health-related question"
    )

    if st.button("Ask AI"):

        if not question.strip():

            st.warning(
                "Please enter a question."
            )

        else:

            with st.spinner("Thinking..."):

                model = genai.GenerativeModel("gemini-2.5-flash")

                try:

                    response = model.generate_content(question)

                    st.write(response.text)

                except Exception as e:

                    st.error(
                        "⚠️ AI Chatbot is temporarily unavailable due to API limit. Please try again later."
                    )
# -----------------------------
# CARETAKER SETTINGS
# -----------------------------

elif menu == "Caretaker Settings":

    # Remove Streamlit form border/box
    st.markdown("""
    <style>
    [data-testid="stForm"] {
        border: none;
        background: transparent;
        padding: 0;
    }
    </style>
    """, unsafe_allow_html=True)

    st.header("👨‍👩‍👧 Caretaker Settings")

    st.info(
        "Add caretaker details for emergency alerts and notifications."
    )

    with st.form("caretaker_form"):

        name = st.text_input(
            "Caretaker Name"
        )

        phone = st.text_input(
            "Caretaker Phone Number"
        )

        email = st.text_input(
            "Caretaker Email"
        )

        submit = st.form_submit_button(
            "💾 Save Caretaker"
        )

    if submit:

        if not name.strip() or not phone.strip() or not email.strip():

            st.warning(
                "Please enter caretaker name, phone number and email."
            )

        elif not re.match(
            r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$",
            email
        ):

            st.error(
                "❌ Please enter a valid email address."
            )

        elif not phone.isdigit():

            st.error(
                "❌ Phone number must contain only digits."
            )

        elif len(phone) != 10:

            st.error(
                "❌ Phone number must contain exactly 10 digits."
            )

        else:

            cursor.execute(
                """
                INSERT INTO caretaker
                (name, phone, email)
                VALUES (?, ?, ?)
                """,
                (name, phone, email)
            )

            conn.commit()

            st.success(
                "✅ Caretaker Saved Successfully"
            )

# -----------------------------
# Expense Intelligence
# -----------------------------

elif menu == "Expense Intelligence":

    st.header("💰 Smart Health Expense Intelligence System")

    # =========================
    # EXPENSE INPUT FORM
    # =========================
    st.subheader("➕ Add New Expense")

    category = st.selectbox(
        "Expense Category",
        ["Medicine", "Doctor Visit", "Lab Test", "Other"]
    )

    amount = st.number_input("Amount (₹)", min_value=0)

    description = st.text_input("Description")

    if st.button("Add Expense"):

        if amount <= 0:
            st.warning("Please enter a valid amount")
        else:
            cursor.execute("""
                INSERT INTO expenses (date, category, amount, description)
                VALUES (?, ?, ?, ?)
            """, (
                datetime.now().strftime("%d-%m-%Y"),
                category,
                amount,
                description
            ))

            conn.commit()

            st.success("Expense Added Successfully")

    # =========================
    # EXPENSE HISTORY 
    # =========================
    st.subheader("📋 Expense History")

    cursor.execute("SELECT * FROM expenses")
    rows = cursor.fetchall()

    if rows:
        for r in rows:
            st.write(f"📅 {r[1]} | {r[2]} | ₹{r[3]} | {r[4]}")
    else:
        st.info("No expenses recorded yet")

    # =========================
    # CATEGORY PIE CHART
    # =========================
    st.subheader("📊 Expense Breakdown")

    cursor.execute("""
        SELECT category, SUM(amount)
        FROM expenses
        GROUP BY category
    """)

    data = cursor.fetchall()

    if data:

        labels = [d[0] for d in data]
        values = [d[1] for d in data]

        fig = go.Figure(data=[go.Pie(labels=labels, values=values)])

        fig.update_layout(height=400)

        st.plotly_chart(fig, use_container_width=True)

    else:
        st.info("No data for chart")

    # =========================
    # MONTHLY TREND GRAPH
    # =========================
    st.subheader("📈 Expense Trend Graph")

    cursor.execute("""
        SELECT date, SUM(amount)
        FROM expenses
        GROUP BY date
    """)

    rows = cursor.fetchall()

    if rows:

        df = pd.DataFrame(rows, columns=["Date", "Amount"])

        df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")

        df = df.sort_values("Date")

        fig = go.Figure()

        fig.add_trace(
            go.Scatter(
                x=df["Date"],
                y=df["Amount"],
                mode="lines+markers"
            )
        )

        fig.update_layout(
            xaxis_title="Date",
            yaxis_title="Expense (₹)",
            height=400
        )

        st.plotly_chart(fig, use_container_width=True)

    else:
        st.info("No trend data available")

    # =========================
    # BUDGET ANALYSIS
    # =========================
    st.subheader("🚨 Budget Analysis")

    monthly_budget = 5000

    cursor.execute("""
        SELECT SUM(amount)
        FROM expenses
    """)

    total = cursor.fetchone()[0] or 0

    st.metric("Total Spent", f"₹{total}")

    if total > monthly_budget:
        st.error("🚨 Budget Exceeded!")

    elif total > monthly_budget * 0.75:
        st.warning("⚠ Near Budget Limit")

    else:
        st.success("🟢 Within Budget")

    # =========================
    # INSURANCE RECOMMENDATION
    # =========================
    st.subheader("🛡 Insurance Recommendation System")

    if total < 2000:
        st.success("Recommended Cover: ₹1–3 Lakhs")
        st.write("Low medical risk profile detected.")

    elif total < 5000:
        st.warning("Recommended Cover: ₹3–7 Lakhs")
        st.write("Moderate medical expense pattern detected.")

    else:
        st.error("Recommended Cover: ₹7–15 Lakhs")
        st.write("High medical expense pattern detected. Consider strong coverage.")

    st.info("Based on your healthcare spending behavior and risk pattern.")

# -----------------------------
# AI Health Risk Forecaster
# -----------------------------

elif menu == "AI Health Risk Forecaster":

    # 1️⃣ Header
    st.header("🧠 AI Health Risk Forecaster")
    st.info("This module predicts patient health risk based on behavior patterns.")

    # 2️⃣ Fetch data
    cursor.execute("SELECT SUM(missed_count) FROM medicines")
    missed = cursor.fetchone()[0] or 0

    cursor.execute("SELECT AVG(health_score) FROM health_history")
    avg_health = cursor.fetchone()[0] 

    if avg_health is None:
       avg_health = 100

    cursor.execute("SELECT SUM(amount) FROM expenses")
    expense = cursor.fetchone()[0] or 0

    # 3️⃣ Calculate risk
    risk_score = 0
    risk_score += min(missed * 5, 50)
    risk_score += (100 - avg_health) * 0.5

    if expense > 5000:
        risk_score += 20
    elif expense > 2000:
        risk_score += 10

    # 🧠 Normalize to percentage
    risk_score = min(risk_score, 120)
    risk_score = (risk_score / 120) * 100


    st.metric("Risk Score", round(risk_score, 2))

    # 4️⃣ Decide risk level
    if risk_score < 30:
        level = "LOW"
        emoji = "🟢"

    elif risk_score < 60:
        level = "MEDIUM"
        emoji = "🟡"

    elif risk_score < 85:
        level = "HIGH"
        emoji = "🔴"

    else:
        level = "CRITICAL"
        emoji = "🚨"

    # 5️⃣ Display result
    st.subheader("🧠 Health Risk Prediction")

    st.markdown(f"## Risk Level: {level} {emoji}")

    st.write("### Reason Analysis:")

    if missed > 0:
        st.write(f"- Missed medicines: {missed}")

    if avg_health < 80:
        st.write("- Health score is declining")

    if expense > 2000:
        st.write("- High medical expenses detected")

    # 6️⃣ Final prediction
    st.write("### Prediction:")

    if level == "CRITICAL":
        st.error("🚨 Critical risk! Immediate medical attention required")

    elif level == "HIGH":
        st.error("🔴 Patient health may worsen in next 7 days")

    elif level == "MEDIUM":
        st.warning("⚠ Moderate risk detected, monitor patient closely")

    else:
        st.success("🟢 Patient is stable and low risk")

# -----------------------------
# AI Health Improvement Coach
# -----------------------------


elif menu == "AI Health Improvement Coach":

    import google.generativeai as genai
    
    try:
        GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]
    except:
        from config import GEMINI_API_KEY

    genai.configure(api_key=GEMINI_API_KEY)

    st.header("🎯 AI Health Improvement Coach")

    st.info(
        "AI-powered personalized recovery planner to improve health score and reduce risk score."
    )

    if "full_plan" not in st.session_state:
        st.session_state.full_plan = ""

    if "summary_text" not in st.session_state:
        st.session_state.summary_text = ""

    # ----------------------------------
    # Fetch Patient Data
    # ----------------------------------

    cursor.execute("SELECT SUM(missed_count) FROM medicines")
    missed = cursor.fetchone()[0] or 0

    cursor.execute("SELECT COUNT(*) FROM medicines")
    total_medicines = cursor.fetchone()[0]
    
    cursor.execute("SELECT COUNT(*) FROM symptoms")
    symptom_count = cursor.fetchone()[0] 

    cursor.execute("SELECT AVG(health_score) FROM health_history")
    avg_health = cursor.fetchone()[0]

    if avg_health is None:
        avg_health = 100
    avg_health = round(avg_health, 2)

    cursor.execute("SELECT SUM(amount) FROM expenses")
    expense = cursor.fetchone()[0] or 0

    # ----------------------------------
    # Risk Score Calculation
    # ----------------------------------

    risk_score = 0

    risk_score += min(missed * 5, 50)

    risk_score += (100 - avg_health) * 0.5

    if expense > 5000:
        risk_score += 20

    elif expense > 2000:
        risk_score += 10

    risk_score = min(risk_score, 120)
    risk_score = (risk_score / 120) * 100
    risk_score = round(risk_score, 2)

    # ----------------------------------
    # Dashboard Metrics
    # ----------------------------------

    col1, col2, col3 = st.columns(3)

    with col1:
        st.metric(
            "Risk Score",
            risk_score
        )

    with col2:
        st.metric(
            "Health Score",
            avg_health
        )

    with col3:
        st.metric(
            "Missed Medicines",
            missed
        )
    

    # ----------------------------------
    # Goal Setting
    # ----------------------------------

    st.subheader("🎯 Set Your Health Goal")

    target_score = st.slider(
        "Target Health Score",
        50,
        100,
        85
    )
    gap = target_score - avg_health

    # ----------------------------------
    # Health Gap Metric
    # ----------------------------------

    st.metric(
        "🎯 Health Score Gap",
        f"{max(0, gap):.1f}"
    )

    st.subheader("🎯 Goal Status")

    st.write(f"Current Health Score: {avg_health:.1f}")
    st.write(f"Target Health Score: {target_score}")

    if gap <= 0:

        st.success(
            f"🎉 Goal Achieved! You are already above your target by {abs(gap):.1f} points."
        )

    else:

        st.warning(
            f"⚠ You need {gap:.1f} more health score points to reach your goal."
        )

    if gap > 0:

        estimated_days = max(
            7,
            int(gap * 1.5)
        )

        st.info(
            f"📅 Estimated time to reach your goal: {estimated_days} days (if you follow the recovery plan consistently)."
        )

    # ----------------------------------
    # Improvement Potential
    # ----------------------------------

    potential_gain = min(
        max(5, missed * 2),
        20
    )

    st.metric(
        "📈 Potential Health Score Gain",
        f"+{potential_gain}"
    )

    # ----------------------------------
    # Today's Priority
    # ----------------------------------

    if missed > 10:

        priority = (
            "Take all scheduled medicines today without skipping."
        )

    elif risk_score > 70:

        priority = (
            "Improve medicine adherence immediately."
        )

    else:

        priority = (
            "Maintain healthy habits and monitor progress."
        )

    st.success(
        f"🎯 Today's Priority: {priority}"
    )

    # ----------------------------------
    # Generate Recovery Plan
    # ----------------------------------

    if st.button("🚀 Generate Recovery Plan"):

        with st.spinner(
            "AI Coach is preparing your personalized recovery roadmap..."
        ):

            model = genai.GenerativeModel(
                "gemini-2.5-flash"
            )

            prompt = f"""
You are an Expert AI Health Improvement Coach.

Analyze the patient information below and create a COMPLETE personalized health improvement roadmap.

PATIENT DATA

Total Medicines: {total_medicines}

Missed Medicines: {missed}

Average Health Score: {avg_health}

Risk Score: {risk_score}

Medical Expenses: {expense}

Target Health Score: {target_score}

Provide the response in EXACTLY TWO SECTIONS.

SECTION 1: QUICK SUMMARY

Include:

1. Today's Priority

2. Today's Action Plan
(3-5 specific actions)

3. Biggest Risk Factor

4. Expected Improvement This Week

Keep this section short and easy to read.

SECTION 2: FULL RECOVERY ROADMAP

Include:

1. Current Health Assessment

2. Root Cause Analysis

3. Biggest Health Problems

4. Medication Discipline Plan

5. Diet Improvement Plan

6. Physical Activity Plan

7. Sleep Improvement Plan

8. Stress Management Plan

9. 7-Day Recovery Roadmap

10. 30-Day Improvement Strategy

11. Expected Health Score Improvement

12. Expected Risk Score Reduction

13. Daily Habits To Follow

14. Today's Most Important Action

15. Long-Term Health Maintenance Tips

Rules:

- Be highly personalized to the patient data.
- Do NOT provide generic advice.
- Focus on increasing health score.
- Focus on reducing risk score.
- Give actionable and practical steps.
- Use bullet points.
- Keep recommendations realistic.
"""

            try:

                response = model.generate_content(
                    prompt
                )

                st.session_state.full_plan = response.text

                st.session_state.summary_text = response.text.split(
                    "SECTION 2:"
                )[0]

            except Exception as e:

                st.error(
                    "⚠️ AI Health Improvement Coach is temporarily unavailable due to Gemini API limit."
                )

                st.info(
                    "Please try again later. Other healthcare features will continue working normally."
                )
        
    if st.session_state.full_plan:

        st.subheader(
            "🎯 Quick Recovery Summary"
        )

        st.write(
            st.session_state.summary_text
        )

        if st.button(
            "📖 View Full Recovery Roadmap"
        ):

            st.subheader(
                "🧠 Complete Recovery Roadmap"
            )

            st.write(
                st.session_state.full_plan
            )

# -----------------------------
# Smart Medication Planner
# -----------------------------

elif menu == "Smart Medication Planner":

    import google.generativeai as genai
    
    try:
        GEMINI_API_KEY = st.secrets["GEMINI_API_KEY"]
    except:
        from config import GEMINI_API_KEY
        
    from datetime import datetime, timedelta

    genai.configure(api_key=GEMINI_API_KEY)

    st.header("💊 Smart Medication Planner")

    st.info(
        "AI-powered medication adherence optimizer and personalized scheduling assistant."
    )

    # ----------------------------------
    # Fetch Medicines
    # ----------------------------------

    cursor.execute("""
    SELECT
        medicine_name,
        medicine_time,
        missed_count
    FROM medicines
    """)

    medicines = cursor.fetchall()

    if not medicines:

        st.warning(
            "No medicines available."
        )

    else:

        # ----------------------------------
        # Adherence Score
        # ----------------------------------

        total_missed = sum(
            med[2]
            for med in medicines
        )

        if total_missed == 0:

            adherence_score = 100

        elif total_missed <= 5:

            adherence_score = 90

        elif total_missed <= 10:

            adherence_score = 75

        elif total_missed <= 20:

            adherence_score = 50

        else:

            adherence_score = 25

        if adherence_score >= 75:

            st.success(
                f"💊 Adherence Score: {adherence_score}%"
            )

        elif adherence_score >= 50:

            st.warning(
                f"💊 Adherence Score: {adherence_score}%"
            )

        else:

            st.error(
                f"💊 Adherence Score: {adherence_score}%"
            )

        # ----------------------------------
        # High Priority Medicines
        # ----------------------------------

        high_risk_count = len(
            [
                med
                for med in medicines
                if med[2] >= 10
            ]
        )

        if high_risk_count > 0:

            st.error(
                f"🚨 High Risk Medicines: {high_risk_count}"
            )

        else:

            st.success(
                "✅ No High Risk Medicines"
            )

        st.divider()

        # ----------------------------------
        # Medicine Analysis Cards
        # ----------------------------------

        for i, med in enumerate(medicines):

            name = med[0]
            current_time = med[1]
            missed = med[2]

            # Risk Level

            if missed >= 10:

                risk = "HIGH 🔴"

            elif missed >= 5:

                risk = "MEDIUM 🟡"

            else:

                risk = "LOW 🟢"

            # Suggested Schedule

            try:

                original_time = datetime.strptime(
                    current_time,
                    "%H:%M:%S"
                )

                if missed >= 10:

                    suggested_time = (
                        original_time -
                        timedelta(minutes=30)
                    ).strftime("%H:%M")

                elif missed >= 5:

                    suggested_time = (
                        original_time -
                        timedelta(minutes=15)
                    ).strftime("%H:%M")

                else:

                    suggested_time = original_time.strftime(
                        "%H:%M"
                    )

            except:

                suggested_time = current_time

            st.markdown(f"""
            <div style="
            background:white;
            padding:20px;
            border-radius:15px;
            margin-bottom:15px;
            border-left:5px solid #2563EB;
            box-shadow:0px 4px 10px rgba(0,0,0,0.1);
            ">
            <h4>💊 {name}</h4>
            <p>⏰ Current Time: {current_time}</p>
            <p>❌ Missed Count: {missed}</p>
            <p>⚠ Risk Level: {risk}</p>
            <p>🎯 Suggested Time: {suggested_time}</p>
            </div>
            """,
            unsafe_allow_html=True)

            if st.button(
                f"🧠 Analyze {name}",
                key=f"analyze_{i}"
            ):

                with st.spinner(
                    "Analyzing adherence pattern..."
                ):

                    model = genai.GenerativeModel(
                        "gemini-2.5-flash"
                    )

                    prompt = f"""
You are an expert medication adherence coach.

Medicine Name:
{name}

Current Schedule:
{current_time}

Missed Count:
{missed}

Risk Level:
{risk}

Suggested Schedule:
{suggested_time}

Explain:

1. Why the patient may be missing doses.

2. How changing the schedule can help.

3. Practical habits to improve adherence.

4. Risks of continuing to miss doses.

Keep the explanation short,
clear and personalized.

Use bullet points.
"""

                    try:

                        response = model.generate_content(
                            prompt
                        )

                        st.success(
                            response.text
                        )

                    except Exception as e:

                        st.error(
                            "⚠️ AI Medication Analysis temporarily unavailable due to Gemini API limit."
                        )

        st.divider()

        timetable = []

        for med in medicines:

            name = med[0]
            current_time = med[1]
            missed = med[2]

            try:

                time_obj = datetime.strptime(
                    current_time,
                    "%H:%M:%S"
                )

                if missed >= 10:

                    optimized = (
                        time_obj -
                        timedelta(minutes=30)
                    ).strftime("%H:%M")

                elif missed >= 5:

                    optimized = (
                        time_obj -
                        timedelta(minutes=15)
                    ).strftime("%H:%M")

                else:

                    optimized = time_obj.strftime(
                        "%H:%M"
                    )

            except:

                optimized = current_time

            timetable.append(
                (optimized, name)
            )

        timetable.sort()

        # ----------------------------------
        # Next Medicine Countdown
        # ----------------------------------

        st.subheader("⏳ Next Medicine Countdown")

        now = datetime.now()

        upcoming_medicines = []

        for time_slot, med_name in timetable:

            try:

                med_time = datetime.strptime(
                    time_slot,
                    "%H:%M"
                )

                med_datetime = now.replace(
                    hour=med_time.hour,
                    minute=med_time.minute,
                    second=0,
                    microsecond=0
                )

                if med_datetime <= now:

                    med_datetime = med_datetime + timedelta(days=1)

                time_difference = med_datetime - now

                upcoming_medicines.append(
                    (
                        time_difference,
                        med_name,
                        time_slot
                    )
                )

            except:

                pass

        if upcoming_medicines:

            upcoming_medicines.sort()

            next_medicine = upcoming_medicines[0]

            remaining_time = next_medicine[0]
            medicine_name = next_medicine[1]
            medicine_time = next_medicine[2]

            hours = remaining_time.seconds // 3600

            minutes = (
                remaining_time.seconds % 3600
            ) // 60

            st.markdown(f"""
            <div style="
            background:linear-gradient(135deg,#FEF3C7,#FDE68A);
            padding:20px;
            border-radius:18px;
            border-left:8px solid #F59E0B;
            box-shadow:0px 4px 12px rgba(0,0,0,0.12);
            margin-bottom:20px;
            ">
            <h3>💊 {medicine_name}</h3>
            <p><b>Scheduled Time:</b> {medicine_time}</p>
            <p><b>Time Remaining:</b> {hours} hour(s) {minutes} minute(s)</p>
            </div>
            """, unsafe_allow_html=True)

        else:

            st.info("No upcoming medicines found.")

        # ----------------------------------
        # Smart Daily Timetable
        # ----------------------------------

        
        st.subheader(
            "📅 Smart Daily Timetable"
        )

        morning = []
        afternoon = []
        evening = []
        night = []

        for time_slot, med_name in timetable:

            hour = int(
                time_slot.split(":")[0]
            )

            if 6 <= hour < 12:

                morning.append(
                    (time_slot, med_name)
                )

            elif 12 <= hour < 17:

                afternoon.append(
                    (time_slot, med_name)
                )

            elif 17 <= hour < 21:

                evening.append(
                    (time_slot, med_name)
                )

            else:

                night.append(
                    (time_slot, med_name)
                )

        # Morning

        if morning:

            st.success("🌅 MORNING")

            for time_slot, med_name in morning:

                st.write(
                    f"⏰ {time_slot} → 💊 {med_name}"
                )

        # Afternoon

        if afternoon:

            st.info("☀ AFTERNOON")

            for time_slot, med_name in afternoon:

                st.write(
                    f"⏰ {time_slot} → 💊 {med_name}"
                )

        # Evening

        if evening:

            st.warning("🌙 EVENING")

            for time_slot, med_name in evening:

                st.write(
                    f"⏰ {time_slot} → 💊 {med_name}"
                )

        # Night

        if night:

            st.error("😴 NIGHT")

            for time_slot, med_name in night:

                st.write(
                    f"⏰ {time_slot} → 💊 {med_name}"
                )

        st.divider()

        # ----------------------------------
        # Overall AI Planner Summary
        # ----------------------------------

        if st.button(
            "🚀 Generate Full AI Medication Plan"
        ):

            with st.spinner(
                "Generating personalized medication strategy..."
            ):

                model = genai.GenerativeModel(
                    "gemini-2.5-flash"
                )

                medicine_data = ""

                for med in medicines:

                    medicine_data += (
                        f"{med[0]} | "
                        f"Time: {med[1]} | "
                        f"Missed: {med[2]}\n"
                    )

                prompt = f"""
You are an expert AI Medication Planner.

Patient Medication Data:

{medicine_data}

Overall Adherence Score:
{adherence_score}

Provide:

1. Medication Adherence Assessment

2. Highest Risk Medicines

3. Daily Medication Strategy

4. Best Reminder Techniques

5. Optimized Schedule Recommendations

6. Weekly Improvement Plan

7. Risks If Non-Adherence Continues

8. Expected Adherence Improvement

Be concise and actionable.

Use bullet points.
"""

                try:

                    response = model.generate_content(
                        prompt
                    )

                    st.subheader(
                        "🧠 AI Medication Improvement Plan"
                    )

                    st.write(
                        response.text
                    )

                except Exception as e:

                    st.error(
                        "⚠️ AI Medication Planner temporarily unavailable due to Gemini API limit."
                    )

        # ----------------------------------
        # AI Daily Routine Planner
        # ----------------------------------

        if st.button(
            "🧠 Generate AI Daily Routine"
        ):

            with st.spinner(
                "Building personalized daily routine..."
            ):

                model = genai.GenerativeModel(
                    "gemini-2.5-flash"
                )

                medicine_data = ""

                for med in medicines:

                    medicine_data += (
                        f"Medicine: {med[0]}\n"
                        f"Time: {med[1]}\n"
                        f"Missed Count: {med[2]}\n\n"
                    )

                prompt = f"""
        You are an expert AI Healthcare Assistant.

        Patient Medication Information:

        {medicine_data}

        Overall Adherence Score:
        {adherence_score}

        Your task is to create a COMPLETE PERSONALIZED DAILY ROUTINE.

        Perform ALL of the following:

        1. Analyze medication adherence patterns.

        2. Identify medicines that are frequently missed.

        3. Create an optimized medication schedule.

        4. Recommend if any medicine should be taken:
        - earlier
        - later
        - with breakfast
        - with lunch
        - with dinner
        - before sleep

        5. Explain WHY schedule changes are recommended.

        6. Create a Daily Routine Planner.

        Include:

        🌅 Morning Routine

        - Wake-up time
        - Water intake
        - Breakfast
        - Medicines

        🏃 Afternoon Routine

        - Lunch
        - Medicines
        - Hydration reminders

        🌙 Evening Routine

        - Dinner
        - Medicines
        - Walking schedule

        😴 Night Routine

        - Bedtime
        - Sleep recommendations
        - Medicines

        7. Create Personalized Schedule Optimization.

        Example:

        07:30 AM → Medicine A
        (Take with breakfast)

        08:00 PM → Medicine B
        (After dinner)

        Explain reasons.

        8. Provide Adherence Improvement Tips.

        Include:

        - Alarm suggestions
        - Pill organizer suggestions
        - Habit stacking suggestions
        - Family/caretaker reminders

        9. Create a Weekly Improvement Plan.

        10. Estimate expected adherence improvement.

        Rules:

        - Be highly personalized.
        - Do NOT give generic advice.
        - Use bullet points.
        - Make recommendations practical.
        - Focus on improving adherence.
        - Focus on reducing missed medicines.
        """

                try:

                    response = model.generate_content(
                        prompt
                    )

                    st.subheader(
                        "🧠 AI Personalized Daily Routine"
                    )

                    st.write(
                        response.text
                    )

                except Exception as e:

                    st.error(
                        "⚠️ AI Daily Routine Generator temporarily unavailable due to Gemini API limit."
                    )
        # ----------------------------------
        # Caretaker Adherence Report
        # ----------------------------------

        st.divider()

        st.subheader("📄 Caretaker Adherence Report")

        if st.button("📧 Generate & Send Caretaker Report"):

            cursor.execute(
                """
                SELECT name, email
                FROM caretaker
                ORDER BY id DESC
                LIMIT 1
                """
            )

            caretaker = cursor.fetchone()

            if not caretaker:

                st.warning(
                    "No caretaker details found. Please add caretaker details first."
                )

            else:

                caretaker_name = caretaker[0]
                caretaker_email = caretaker[1]

                high_risk_medicines = []

                for med in medicines:

                    if med[2] >= 10:

                        high_risk_medicines.append(
                            f"- {med[0]} missed {med[2]} times"
                        )

                if high_risk_medicines:

                    high_risk_text = "\n".join(
                        high_risk_medicines
                    )

                else:

                    high_risk_text = "No high-risk medicines detected."

                report = f"""
Dear {caretaker_name},

This is an automated patient medication adherence report from Smart Healthcare Assistant.

Patient Medication Status:

Adherence Score: {adherence_score}%

Total Missed Medicines: {total_missed}

High Risk Medicines:
{high_risk_text}

Concern:
The patient may need additional support with medicine adherence. Repeatedly missing medicines can reduce treatment effectiveness and may increase health risks.

Recommended Caretaker Actions:

- Remind the patient before scheduled medicine time.
- Supervise high-risk medicines closely.
- Keep medicines near daily routines such as breakfast, lunch or dinner.
- Use phone alarms or a pill organizer.
- Monitor the patient carefully for the next 7 days.
- Contact a doctor if medicines are continuously missed.

Generated by Smart Healthcare Assistant.
"""

                try:

                    send_caretaker_report_email(
                        caretaker_email,
                        report
                    )

                    st.success(
                        f"📧 Caretaker report sent successfully to {caretaker_email}"
                    )

                except Exception as e:

                    st.error(
                        f"Email sending failed: {e}"
                    )

                st.text_area(
                    "Generated Report Preview",
                    report,
                    height=350
                )
# -----------------------------
# CLOSE CONNECTION
# -----------------------------

conn.close()
